################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c \
F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c 

C_DEPS += \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.d \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.d 

OBJS += \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.o \
./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.o 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.o: F:/Marcin/Documents/Studia/PGRacing/PGRacingElectronics/Dashboard/code/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c Drivers/STM32F7xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-STM32F7xx_HAL_Driver

clean-Drivers-2f-STM32F7xx_HAL_Driver:
	-$(RM) ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.o ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.d ./Drivers/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.o

.PHONY: clean-Drivers-2f-STM32F7xx_HAL_Driver

